app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('prices', views.PricesView.as_view(), name='prices'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('register-courses', views.RegisterCoursesView.as_view(), name='register_courses'),
    path('search', views.SearchView.as_view(), name='search'),

    path('tutors/<int:pk>', views.tutor_view, name='tutor_detail'),

    path('testing', views.ForTestingView.as_view()),

    path('ajax/load-subjects/', views.load_subjects, name='ajax_load_subjects'),
    path('ajax/load-levels/', views.load_levels, name='ajax_load_levels'),
]

privatmalta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    # BUG: use path() instead of url() for consistency's sake
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
]

app/models.py
from django.db import models
from django.core.validators import RegexValidator, MaxValueValidator, MinValueValidator

class Locality(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'localities'


class Subject(models.Model):

    CATEGORY_CHOICES = (
        ('academic', 'academic'),
        ('sports', 'sports'),
        ('music', 'music'),
    )

    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)

    def __str__(self):
        return self.name


class Tutor(models.Model):

    def path_and_filename(instance, filename):
        upload_to = 'images/tutors-profile'
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(uuid4().hex, ext)
        return os.path.join(upload_to, filename)

    TITLE_CHOICES = (
        ('Mr', 'Mr'),
        ('Mrs', 'Mrs'),
        ('Miss', 'Miss'),
        ('Ms', 'Ms'),
        ('Dr', 'Dr'),
        ('Prof', 'Prof'),
        ('Rev', 'Rev'),
        ('Hon', 'Hon'),
        ('Sir', 'Sir'),
        ('Ing', 'Ing'),
    )

    title = models.CharField(max_length=10, choices=TITLE_CHOICES)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    address = models.CharField(max_length=120)
    # post_code =
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, null=True)

    registration_date = models.DateTimeField(auto_now_add=True)

    bio1 = models.TextField()
    bio2 = models.TextField()
    bio3 = models.TextField()

    phone_regex = RegexValidator(regex=r'^\d{8}$', message="Phone number must be exactly 8 digits long.")

    tel = models.CharField(
        validators=[phone_regex],
        max_length=8,
        blank=True,
        verbose_name="Telephone",
    )

    mob = models.CharField(
        validators=[phone_regex],
        max_length=8,
        blank=True,
        verbose_name="Mobile",
    )

    email = models.EmailField()

    # BUG: null=True necessary?
    profile_pic = models.ImageField(upload_to=path_and_filename, null=True)

    def __str__(self):
        return '%s %s %s' % (self.title, self.first_name, self.last_name)


class TutorGalleryPic(models.Model):
    def path_and_filename(instance, filename):
        upload_to = 'images/tutors-other'
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(uuid4().hex, ext)
        return os.path.join(upload_to, filename)

    tutor = models.ForeignKey(Tutor, related_name='images', on_delete = models.DO_NOTHING)
    image_path = models.ImageField(upload_to=path_and_filename)


class Level(models.Model):
    # BUG: PENDING: Make the two fields unique_together
    category = models.CharField(max_length=20, choices=Subject.CATEGORY_CHOICES)
    level = models.CharField(max_length=60)

    def __str__(self):
        return self.level


class Course(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    category = models.CharField(max_length=20, choices=Subject.CATEGORY_CHOICES)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    # level = models.CharField(max_length=40, choices=LEVEL_CHOICES)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    price = models.PositiveSmallIntegerField()

    def __str__(self):
        return "%s (%s) - %s" % (self.subject, self.level, self.tutor)

class Review(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    # reviewer_fb_id =
    rating = models.PositiveSmallIntegerField(
        validators = [MaxValueValidator(5), MinValueValidator(1)]
    )
    review_text = models.TextField()
    review_date = models.DateTimeField(auto_now_add=True)

app/forms.py
from django.forms import ModelForm
from app.models import Tutor, Course, Subject, Level

class RegisterForm(ModelForm):
    class Meta:
        model = Tutor
        exclude = ['registration_date', 'profile_pic']

class RegisterCoursesForm(ModelForm):
    class Meta:
        model = Course
        fields = ('tutor', 'category', 'subject', 'level', 'price')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subject'].queryset = Subject.objects.none()
        self.fields['level'].queryset = Level.objects.none()

app/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, DetailView
from django.shortcuts import render

from .forms import RegisterForm, RegisterCoursesForm
from .models import Tutor, TutorGalleryPic, Subject, Level, Course

class HomePageView(TemplateView):
    template_name = 'home.html'

class PricesView(TemplateView):
    template_name = 'prices.html'

class RegisterView(CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('register_courses')
    template_name = 'register.html'

class RegisterCoursesView(CreateView):
    form_class = RegisterCoursesForm
    # success_url
    template_name = 'register_courses.html'

def tutor_view(request, pk):
    my_context = {
        'tutor': Tutor.objects.get(pk=pk),
        'courses': Course.objects.filter(tutor=pk),
        # 'reviews': Review.objects.filter(tutor=pk),
        'gallery': TutorGalleryPic.objects.filter(tutor=pk),}
    return render(request, 'tutor_detail.html', context=my_context)

class SearchView(TemplateView):
    template_name = 'search.html'

class ForTestingView(TemplateView):
    template_name = 'still_being_tested/1_slider.html'

def load_subjects(request):
    subjects = Subject.objects.filter(category=request.GET.get('category')).order_by('name')
    return render(request, 'dropdown_list_options_for_subject.html', {'subjects': subjects})

def load_levels(request):
    levels = Level.objects.filter(category=request.GET.get('category')).order_by('id')
    return render(request, 'dropdown_list_options_for_level.html', {'levels': levels})

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href={% static "css/base.css" %}>

    {% block other_stylesheets %}
    {% endblock %}

    <title>{% block title %}Privat Malta{% endblock title %}</title>
  </head>
  <body>
    <main>
      {% block content %}
      {% endblock %}
    </main>

    <div id="footer" class="jumbotron">
      <div class="row">
        <div class="col-sm-3">
          <p style="width: 70%;">PrivatMalta is an online phone directory of Malta's private tutors.</p>
          <p></p>
          <p style="margin-bottom: 1px;"><strong>info@privatmalta.com</strong></p>
          <p>+(356) 99 123 123</p>
        </div>
        <div class="col-sm-3">
          <ul class="list-unstyled">
            <li><a href="{% url 'register' %}">Register as a tutor</a></li>
            <li><a href="#">Advertise</a></li>
            <li><a href="#">Sign in</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Users Reviews</a></li>
            <li><a href="#">FAQ</a></li>
          </ul>
        </div>
        <div class="col-sm-3">
          <ul class="list-unstyled">
            <li><a href="#">Terms of Use</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-sm-3">
          <a href="#" class="fa fa-facebook"></a>
          <a href="#" class="fa fa-twitter"></a>
          <a href="#" class="fa fa-youtube"></a>
          <a href="#" class="fa fa-instagram"></a>
        </div>
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    {% block other_js_scripts %}
    {% endblock %}

    {%block js_code %}
    {% endblock %}
  </body>
</html>

templates/dropdown_list_options_for_level.html
<option value="">----------</option>
{% for level in levels %}
<option value="{{ level.pk }}">{{ level.level }}</option>
{% endfor %}

templates/dropdown_list_options_for_subject.html
<option value="">-----------</option>
{% for subject in subjects %}
<option value="{{ subject.pk }}">{{ subject.name }}</option>
{% endfor %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<p>Welcome to home page!</p>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Register</button>
  </form>
{% endblock %}

templates/register_courses.html
{% extends 'base.html' %}

{% block title %}Register Courses{% endblock %}

{% block content %}
  <h2>Register the courses you are offering:</h2>
  <form method="post" id="registerCoursesForm" data-subjects-url="{% url 'ajax_load_subjects' %}" data-levels-url="{% url 'ajax_load_levels' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Add Course</button>
    <a href="#">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_category").change(function () {

      var categoryId = $(this).val();  // get the selected category ID from the HTML input

      var url = $("#registerCoursesForm").attr("data-subjects-url");  // get the url of the `load_subjects` view

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/ajax/load-subjects/)
        data: {
          'category': categoryId  // add the category id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subjects` view function
          $("#id_subject").html(data);  // replace the contents of the subject dropdown with the data that came from the server
        }
      });

      var url = $("#registerCoursesForm").attr("data-levels-url");

      $.ajax({
        url: url,
        data: {
          'category': categoryId
        },
        success: function (data) {
          $("#id_level").html(data);
        }
      });

    });
  </script>

{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Search Results{% endblock %}

{% block content %}
<div class="row">
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!_L_E_F_T_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <div class="col-lg-2">
    <div class="container" id="left_panel">
      <div class="card bg-info text-white">
        <form action="#">
          <h4>Filters</h4>
          <div class="form-check">
            <label class="form-check-label" for="check1">
              <input type="checkbox" class="form-check-input" id="check1" name="option1" value="something">Wheelchair-accessible
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label" for="check2">
              <input type="checkbox" class="form-check-input" id="check2" name="option2" value="something">Streamed Classes
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input">Lessons in English
            </label>
          </div>
          <button type="submit" class="btn btn-primary">Apply filters</button>
        </form>
      </div>
      <div class="card bg-info text-white">
        <form action="#">
          <h4>Search Tutor</h4>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Enter tutor's name . . .">
            <div class="input-group-append">
              <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
             </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!_C_E_N_T_E_R!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <div class="col-lg-8">
    <div class="container" id="tutor_cards_container">
      <!-- RESULTS HEADER (start) -->
      <div class="card">
        <div class="row">
          <div class="col-lg-6">
            <p>3 tutors found</p>
          </div>
          <div class="col-lg-6">
            <form action="">
              <div class="form-group">
                <label for="sortby_dropdown">Sort by:</label>
                <select onchange="this.form.submit()" class="form-control" id="sortby_dropdown">
                  <option>Relevance</option>
                  <option>Rating</option>
                  <option>Price</option>
                  <option>Distance</option>
                </select>
                <br>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- RESULTS HEADER (end) -->
      <!-- TUTOR CARDS (start) -->
      {% for i in "xxx" %}
      <div class="card">
        <div class="container">
          <div class="row">
            <div class="col-lg-3">
            <img class="card-img-top" src={% static "images/img_avatar1.png" %} alt="Card image" style="width:100%">
            <p style="text-align:center">&#9733;&#9733;&#9733;&#9733;&#9733;</p>
            <p style="text-align:center"><small>46 reviews</small></p>
            </div>
            <div class="col-lg-9">
              <div class="card-body">
                <h4 class="card-title">Dr. Thomas Scicluna</h4>
                <p>
                  <a href="#" class="card-link">99 983 475</a>
                  <a href="#" class="card-link">tscicluna@gmail.com</a>
                </p>
                <small><em>Triq id-Dundjan, Ħal Qormi</em></small>
                <p class="card-text">Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
                <kbd>physics</kbd> <kbd>mathematics</kbd>
              </div>
            </div>

          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- TUTOR CARDS (finish) -->
  </div>
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!_R_I_G_H_T_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
  <div class="col-lg-2">
    <img src={% static "images/advert.gif" %} style="width:100%">
  </div>

</div>





{% endblock %}

templates/still_being_tested/1_slider.html
{% extends 'base.html' %}

{% block content %}
  <h1>Testing Page</h1>
  <div style="color:red">
    <h4>bootstrap-slider.js</h4>
    <p>Mission: Update the values at the sides when slider moves.</p>
    <p>Problem: 'change' event not being registered.</p>
  </div>
  <p>Number of students:</p>
  <b id="classSizeMin">€ 10</b>
  <input id="classSize"
            onclick="foobar()"
            type="text"
            class="span2"
            value=""
            data-slider-min="1"
            data-slider-max="30"
            data-slider-step="1"
            data-slider-value="[6,15]"/>
  <b id="classSizeMax">€ 1000</b>
{% endblock %}

{% block other_js_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/bootstrap-slider.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css">
{% endblock %}

{% block js_code %}
  <script>
    var mySlider = new Slider('#classSize', {});

    document.getElementById("classSize").addEventListener('click', function(){
      alert("SLID!");
    });

    // slider.getValue()[0] // min value
    // slider.getValue()[1] // max value

    function foobar() {
      alert("You clicked!");
      document.getElementById("classSizeMin").innerHTML = "LOL";
    }


  </script>
{% endblock %}

templates/subject_dropdown_list_options.html
<option value="">-----------</option>
{% for subject in subjects %}
<option value="{{ subject.pk }}">{{ subject.name }}</option>
{% endfor %}

templates/tutor_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block other_stylesheets %}
<link rel="stylesheet" href={% static "css/tutor_detail.css" %}>

{% endblock %}

{% block title %}{{tutor}}{% endblock %}

{% block content %}
  <div id="section1" class="jumbotron">
    <h1>{{tutor}}</h1>
    <h2>Session & Demo Vocalist</h2>
    <p>&#9733;&#9733;&#9733;&#9733;&#9733;55 reviews (51 Verified)</p>
    <p>{{tutor.address}}</p>
  </div>
  <div id="section2" class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="#bio">Bio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#courses">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#reviews">Reviews (55)</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#interview">Interview</a>
          </li>
        </ul>
      </div>
      <div class="col-sm-6">
        <button type="button" class="btn btn-success btn-lg" style="float: right;">Contact {{ tutor.first_name }}</button>
      </div>
    </div>
  </div>
  <div id="section3" class="container">
    <div style="margin-top: 0px;" class="row">
      <div class="col-sm-8">
        <div id="bio" class="container">
          <p style="padding-top: 50px;"><strong>{{tutor.bio1}}</strong></p>
          <p>{{tutor.bio2}}</p>
          <p><strong>{{tutor.bio3}}</strong></p>
        </div>
        <hr>
        <div id="courses" class="container">
          <h3 style="text-align: left; margin-bottom: 20px;">Courses</h3>
            <table id="coursesTable" class="table" style="width:100%">
              <thead class="thead-light">
                <tr>
                  <th>Category</th>
                  <th>Subject</th>
                  <th>Level</th>
                  <th>Price</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for course in courses %}
                <tr>
                  <td>{{course.category}}</td>
                  <td>{{course.subject}}</td>
                  <td>{{course.level}}</td>
                  <td>€ {{course.price}}</td>
                  <td> <button type="button" class="btn btn-outline-success">Book now!</button> </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        <hr>
        <div id="reviews" class="container">
          <h3>55 Reviews</h3>
          {% for review in 'xxxxx' %}
            <div class="card review">
              <div class="card-header">
                <img src={% static "images/img_avatar1.png" %} style="width:65px">
                <p>&#9733;&#9733;&#9733;&#9733;&#9733;</p>
                <p class="font-weight-light small">19 days ago by <a href="#"><strong>Timothy Ellul</strong></a></p>
              </div>
              <div class="card-body">
                <p>Vestibulum euismod varius ante, at lacinia dui posuere non. Morbi fermentum, lectus nec fermentum interdum, quam urna blandit tortor, quis mattis felis augue quis tellus.</p>
              </div>
              <!-- <div class="card-footer">Footer</div> -->
            </div>
          {% endfor %}
        </div>
      </div>
      <div id="adverts_col" class="col-sm-4">
        <div class="card advert">
          <p>advert</p>
        </div>
        <div id="more_photos" class="card">
          <div class="card-header">
            <h5>More photos</h5>
          </div>
          <div class="card-body">
            {% for img in gallery %}
              <img src="{{ MEDIA_URL }}{{ img.image_path }}" alt="failed to load" style="width:40px">
            {% endfor %}
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h5>Payment Policy</h5>
          </div>
          <div class="card-body">
            <p>Lessons are paid for in advance. Refunds are given only on presentation of doctor's certificate.</p>
          </div>

        </div>
        <div class="card advert">
          <p>advert</p>
        </div>
        <div class="card">
          lolol
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tutor_detail_OLD.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{tutor}}{% endblock %}

{% block content %}
  {% if tutor %}
    <div class="container">


      <div class="card">
        <div class="container">
          <div class="row">
            <div class="col-lg-3">
            <img class="card-img-top" src={% static "images/img_avatar1.png" %} alt="Card image" style="width:100%">
            <p style="text-align:center">&#9733;&#9733;&#9733;&#9733;&#9733;</p>
            <p style="text-align:center"><small>46 reviews</small></p>
            </div>
            <div class="col-lg-9">
              <div class="card-body">
                <h4 class="card-title">Dr. Thomas Scicluna</h4>
                <p>
                  <a href="#" class="card-link">99 983 475</a>
                  <a href="#" class="card-link">tscicluna@gmail.com</a>
                </p>
                <small><em>Triq id-Dundjan, Ħal Qormi</em></small>
                <p class="card-text">Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
                <kbd>physics</kbd> <kbd>mathematics</kbd>
              </div>
            </div>

          </div>
        </div>
      </div>




      <h2>{{tutor}}</h2>
      <p>{{tutor.address}}</p>
      <p>{{tutor.locality}}</p>
      <p>Registered: {{tutor.registration_date}}</p>
      <p>{{tutor.tel}}</p>
      <p>{{tutor.mob}}</p>
      <p>{{tutor.email}}</p>

      <h3>Courses</h3>
      {% if courses %}
        <table style="width:100%">
          <tr>
            <th>Category</th>
            <th>Subject</th>
            <th>Level</th>
            <th>Price</th>
            <th></th>
          </tr>
          {% for course in courses %}
          <tr>
            <td>{{ course.category }}</td>
            <td>{{ course.subject }}</td>
            <td>{{ course.level }}</td>
            <td>€ {{ course.price }}</td>
            <td> <button type="button" name="button">Book now!</button> </td>
          </tr>
          {% endfor %}
        </table>
      {% endif %}

    </div>
  {% endif %}
{% endblock content %}